name: Build Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Native DLL (CMake)
        run: |
          cd ./tools/asar-fuses-bypass
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release

      - name: Publish EXE
        run: dotnet publish Wemod-Patcher.sln -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WemodPatcher-Executable
          path: '**/bin/Release/net*/**/*.exe'
